# Function makeCacheMatrix sets the values of a matrix and caches its values, as well
# as it creates a variable called inverse.
# The next function (cacheSolve) calculates the inverted matrix that is generated by the previous
# function. See below:


# Function makeCacheMatrix:
# This function contains a total of four functions:
# 1) setmatrix: a function that sets the values of a matrix
# 2) getmatrix: a function returning the matrix stored from setmatrix function
# 3) setinverse: a function creating a variable called inverse
# 4) getinverse: a function returning the value of the variable called inverse

makeCacheMatrix <- function(x = matrix()) {
  inverse <- matrix()
  
  setmatrix <- function(y) {
    x <<- y
    inverse <<- matrix()
  }
  getmatrix <- function() x
  
  setinverse <- function(inverse) inverse <<- inverse
  
  getinverse <- function() inverse
  
  list(setmatrix = setmatrix, getmatrix = getmatrix,
       setinverse = setinverse,
       getinverse = getinverse)
}


# This function starts by checking that the variable "inverse" is not a NA, in which case
# it then goes on inverting our matrix and showing the result.

cacheSolve <- function(x, ...) {
    inverse <- x$getinverse()   
    if (!is.na(inverse)){
      message("getting cached data")
      return(inverse)
    }
    
    mymatrix <- x$getmatrix()
    inverse <- solve(mymatrix, ...)
    x$setinverse(inverse)
    inverse
}
